import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set page configuration
st.set_page_config(page_title="Coffee Shop Sales Analysis", layout="wide")

# Set plotting style
sns.set_theme(style="whitegrid")

# Helper function to load data
@st.cache_data
def load_data():
    try:
        df = pd.read_csv('coffee_shop_sales.csv')
        df['Date'] = pd.to_datetime(df['Date'])
        df['Month_Period'] = df['Date'].dt.to_period('M')
        df['Month_Str'] = df['Date'].dt.strftime('%Y-%m') # String for filtering
        df['Hour'] = pd.to_datetime(df['Time'], format='%H:%M').dt.hour
        return df
    except FileNotFoundError:
        return None

# --- APP LAYOUT ---

st.title("☕ Coffee Shop Sales Analysis Dashboard")
st.markdown("Interactive analysis of sales performance, customer trends, and product popularity.")

# Load Data
df = load_data()

if df is None:
    st.error("Error: 'coffee_shop_sales.csv' not found. Please run 'generate_data.py' first to create the dataset.")
    st.stop()

# --- SIDEBAR FILTERS ---
st.sidebar.header("Filter Options")

# Date Filter (Month)
available_months = sorted(df['Month_Str'].unique())
selected_month = st.sidebar.selectbox("Select Month", ["All Months"] + available_months)

# Filter Data based on selection
if selected_month != "All Months":
    filtered_df = df[df['Month_Str'] == selected_month]
    st.sidebar.success(f"Showing data for: {selected_month}")
else:
    filtered_df = df
    st.sidebar.info("Showing data for all months")

# --- KPI METRICS ---
st.markdown("### 📊 Key Performance Indicators")
col1, col2, col3, col4 = st.columns(4)

total_revenue = filtered_df['Total Spent'].sum()
avg_transaction = filtered_df['Total Spent'].mean()
total_transactions = len(filtered_df)
peak_hour = filtered_df.groupby('Hour')['Transaction ID'].count().idxmax() if not filtered_df.empty else 0

col1.metric("Total Revenue", f"${total_revenue:,.2f}")
col2.metric("Avg Transaction", f"${avg_transaction:.2f}")
col3.metric("Total Transactions", f"{total_transactions:,}")
col4.metric("Peak Hour", f"{peak_hour}:00")

st.markdown("---")

# --- VISUALIZATIONS ---

# Row 1: Revenue Trend & Category Sales
col_left, col_right = st.columns(2)

with col_left:
    st.subheader("Monthly Revenue Trend")
    if selected_month == "All Months":
        fig1, ax1 = plt.subplots(figsize=(10, 5))
        monthly_sales = filtered_df.groupby('Month_Period')['Total Spent'].sum()
        monthly_sales.index = monthly_sales.index.astype(str)
        sns.lineplot(x=monthly_sales.index, y=monthly_sales.values, marker='o', color='b', ax=ax1)
        ax1.set_xlabel('Month')
        ax1.set_ylabel('Total Revenue ($)')
        plt.xticks(rotation=45)
        st.pyplot(fig1)
    else:
        st.info("Select 'All Months' to view the yearly trend.")

with col_right:
    st.subheader("Sales by Category")
    fig2, ax2 = plt.subplots(figsize=(10, 5))
    category_sales = filtered_df.groupby('Category')['Total Spent'].sum().sort_values(ascending=False)
    sns.barplot(x=category_sales.index, y=category_sales.values, hue=category_sales.index, palette='viridis', legend=False, ax=ax2)
    ax2.set_ylabel('Revenue ($)')
    st.pyplot(fig2)

# Row 2: Hourly Transactions & Top Items
col_left_2, col_right_2 = st.columns(2)

with col_left_2:
    st.subheader("Hourly Transaction Volume")
    fig3, ax3 = plt.subplots(figsize=(10, 5))
    hourly_counts = filtered_df.groupby('Hour')['Transaction ID'].count()
    # Ensure all hours 0-23 are represented for clean plot if filtering
    # (Optional, but keeps x-axis consistent)
    sns.barplot(x=hourly_counts.index, y=hourly_counts.values, hue=hourly_counts.index, palette='coolwarm', legend=False, ax=ax3)
    ax3.set_xlabel('Hour of Day')
    ax3.set_ylabel('Transactions')
    st.pyplot(fig3)

with col_right_2:
    st.subheader("Top 10 Best-Selling Items")
    fig4, ax4 = plt.subplots(figsize=(10, 5))
    top_10_items = filtered_df.groupby('Item')['Quantity'].sum().sort_values(ascending=False).head(10)
    sns.barplot(y=top_10_items.index, x=top_10_items.values, hue=top_10_items.index, palette='magma', orient='h', legend=False, ax=ax4)
    ax4.set_xlabel('Quantity Sold')
    st.pyplot(fig4)

# Row 3: Payment Distribution
st.subheader("Payment Method Distribution")
fig5, ax5 = plt.subplots(figsize=(6, 6))
payment_counts = filtered_df['Payment Method'].value_counts()
if not payment_counts.empty:
    ax5.pie(payment_counts, labels=payment_counts.index, autopct='%1.1f%%', colors=sns.color_palette('pastel'), startangle=140)
    st.pyplot(fig5)
else:
    st.write("No data available for payment distribution.")

st.markdown("---")
st.caption("Dashboard generated by Streamlit • Data Source: coffee_shop_sales.csv")
